### PR TITLE
fix: Port 4000 is already occupied

### LINKED ISSUE #29: Jekyll run thinks port 4000 is occupied
Jekyll run shows the message "Port 4000 is already occupied by process: XYZ Either kill that process or use another port in _config.yml" when clicking the jekyll-run button with a jekyll repo opened.

PID XYZ is the virus software on my laptop, but it's not occupying that port. Running "bundle exec jekyll s" from WSL or powershell in the jekyll project dir serves the site perfectly fine on port 4000.

Changing the port in the plugin config does not seem to change the error. In the screenshot below I changed to 3000, restarted vs code, opened a file in the jekyll repo and clicked the jekyll run button.

afbeelding

Running versions:
afbeelding

Please let me know what kind of info I can add and how to investigate.

### PR DESCRIPTION
**Pull request by chriskyfung**
This PR fixes #29 with the following changes:

- Stop Jekyll server before exiting VS Code within `deactivate()`.
- Enable user easily changes the port and the base URL configuration in the extension settings.
- Deprecated `openLocalJekyllSite()` in `open-in-browser.ts`
- Changed to get the server address (_including the **port** and **base URL**_) from stdout.
- Replaced `openLocalJekyllSite()` with `openUrl()`

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -452,4 +467,17 @@ export function activate(context: ExtensionContext) {
 }
 
 // this method is called when your extension is deactivated
-export function deactivate() { }
+export function deactivate() {
```
Comment (Kanna727) [inline src/extension.ts:466]: I think the ability to stop Jekyll server before exiting VS Code should be an option to users which can be set in the extension settings with default being false. Let me know your thoughts

File: src/extension.ts [hunk 2]
```diff
@@ -452,4 +467,17 @@ export function activate(context: ExtensionContext) {
...
+    console.log("Exit VSCode. Stopping: " + pid);
+    if (currWorkspace && isRunning) {
```
Comment (Kanna727) [inline src/extension.ts]: This code is duplicate of [Stop command](https://github.com/chriskyfung/jekyll-run/blob/master/src/extension.ts#L386). Please extract this into a separate function and use it at both the places

File: src/extension.ts [hunk 3]
```diff
@@ -34,27 +40,36 @@ enum Icons {
...
+        baseurlInArgs = m_baseurl[2];
+    };
+    return { 
+        port: m_port ? true : false,
+        baseurl: m_baseurl ? true : false
+    };
 }
 
-function checkConfigAndGetBaseUrl(currWorkspace: WorkspaceFolder): boolean {
+function checkConfigAndGetPort(currWorkspace: WorkspaceFolder): boolean {
```
Comment (Kanna727) [inline src/extension.ts]:
```suggestion
function getPortAndBaseurl(currWorkspace: WorkspaceFolder): boolean {
```

File: src/extension.ts [hunk 4]
```diff
@@ -76,14 +91,12 @@ function isStaticWebsiteWorkspace(): boolean {
         if (resource.scheme === 'file') {
             currWorkspace = workspace.getWorkspaceFolder(resource);
             if (currWorkspace) {
-                checkConfigAndGetBaseUrl(currWorkspace);
                 return checkConfigAndGetPort(currWorkspace);
```
Comment (Kanna727) [inline src/extension.ts]:
```suggestion
                return getPortAndBaseurl(currWorkspace);
```

File: src/extension.ts [hunk 5]
```diff
@@ -76,14 +91,12 @@ function isStaticWebsiteWorkspace(): boolean {
...
             }
         }
     } else {
         currWorkspace = workspace.workspaceFolders[0];
         if (currWorkspace) {
-            checkConfigAndGetBaseUrl(currWorkspace);
             return checkConfigAndGetPort(currWorkspace);
```
Comment (Kanna727) [inline src/extension.ts]:
```suggestion
            return getPortAndBaseurl(currWorkspace);
```

File: src/extension.ts [hunk 6]
```diff
@@ -34,27 +40,36 @@ enum Icons {
...
+    if (m_port) {
+        portInArgs = parseInt(m_port[2]);
+    };
+    if (m_baseurl) {
+        baseurlInArgs = m_baseurl[2];
+    };
+    return { 
+        port: m_port ? true : false,
+        baseurl: m_baseurl ? true : false
+    };
```
Comment (Kanna727) [inline src/extension.ts]:
```suggestion
```

File: src/extension.ts [hunk 7]
```diff
@@ -34,27 +40,36 @@ enum Icons {
...
         var read = require('read-yaml');
         var config = read.sync(configPath);
 
         console.log(config);
+        if (config.port !== undefined) { portInConfig = config.port; }
         if (config.baseurl !== undefined) { baseurlInConfig = config.baseurl; }
+
+        const configInArgs = getConfigFromArgs();
+        serverPort = configInArgs.port? portInArgs : portInConfig;
+        serverBaseurl = configInArgs.baseurl? baseurlInArgs : baseurlInConfig;
```
Comment (Kanna727) [inline src/extension.ts]:
```suggestion
        getConfigFromArgs();
        serverPort = portInArgs || portInConfig;
        serverBaseurl = baseurlInArgs || baseurlInConfig;
```

File: src/cmds/run.ts [hunk 8]
```diff
@@ -44,8 +45,12 @@ export class Run {
             var strString = data.toString();
             outputChannel.append(strString);
             outputChannel.show(true);
+            if (strString.includes('Server address')) {
+              const match = strString.match(/Server address: (\S+)/m);
+              this.address = match ? match[1] : `http://localhost:${serverPort}`;
```
Comment (Kanna727) [inline src/cmds/run.ts]:
```suggestion
              this.address = match?.[1]  || `http://localhost:${serverPort}`;
```

File: src/extension.ts [hunk 9]
```diff
@@ -200,7 +213,7 @@ export function activate(context: ExtensionContext) {
 
     const open = commands.registerCommand('jekyll-run.Open', async () => {
         if (isStaticWebsiteWorkspace() && currWorkspace && isRunning) {
-            openLocalJekyllSite(portInConfig, baseurlInConfig);
+            openUrl(address);
```
Comment (Kanna727) [inline src/extension.ts:212]: Please change the default parameter value of [`openUrl`](https://github.com/chriskyfung/jekyll-run/blob/master/src/utils/open-in-browser.ts#L4) function to `http://127.0.0.1:4000`. Unfortunately, GitHub is not allowing me to comment on an unchanged line. Sorry for the inconvenience.

**Review by Kanna727 — CHANGES_REQUESTED** [review]

**Comment by Kanna727** [comment]
@chriskyfung Thanks a lot for the PR. Please complete the below tasks. Once done, I'll merge the PR.

- [ ] Do the review changes. Feel free to discuss.

File: src/extension.ts (hunk 1 above)
Comment (chriskyfung) [reply src/extension.ts:466]: I think we can add an option in the extension settings but I prefer to stop Jekyll when exit VS Code. Otherwise, it is painful to restore the port and unable to monitor the Jekyll server in a new VS Code window.

I have no idea about why the Jekyll should continue to run in the background.

File: src/extension.ts (hunk 2 above)
Comment (chriskyfung) [reply src/extension.ts]: Make sense!

File: src/extension.ts (hunk 1 above)
Comment (chriskyfung) [reply src/extension.ts:466]: Can you suggest a name for the new extension setting? That I add it to the `deactivate()` and `package.json`.

File: src/extension.ts (hunk 2 above)
Comment (chriskyfung) [reply src/extension.ts]: I changed to stop the server in `deactivate()` using the following code:

```ts
commands.executeCommand('jekyll-run.Stop');
```

I think it will be simpler and maintainable.

File: src/extension.ts (hunk 1 above)
Comment (chriskyfung) [reply src/extension.ts:466]: I made a draft as belows:

```json
# package.json
"jekyll-run.stopServerOnExit": {
	"type": "boolean",
	"description": "Stop Jekyll server before exiting VS Code",
	"default": "false"
}
```

```ts
# extension.ts
export function deactivate() {
    const config = Config.get();
    if (config.stopServerOnExit) {
        console.log("Exit VSCode. Stopping: " + pid);
        commands.executeCommand('jekyll-run.Stop');
    }
}
```

Comment (Kanna727) [reply src/extension.ts:466]: Thanks @chriskyfung. Sometimes users might want just the extension to stop but not the server. So, let's provide this option for users to do whatever they want

**Review by Kanna727 — APPROVED** [review]

**Comment by Kanna727** [comment]
Hi @chriskyfung, I forgot to mention but could you please submit another PR with updated README that explains the new config we've added?
